# Generated by Django 5.0.6 on 2024-06-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food_details",
            name="price",
        ),
    ]
