# Generated by Django 5.0.6 on 2024-06-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_food_details_calories_food_details_serving_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="type_of_food",
        ),
        migrations.AlterField(
            model_name="food_details",
            name="calories",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="food_details",
            name="serving_size",
            field=models.IntegerField(),
        ),
    ]
