# Generated by Django 5.0.6 on 2024-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_rename_unit_ingredient_type_of_food_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_details",
            name="calories",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="food_details",
            name="carbs",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="food_details",
            name="fat",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="food_details",
            name="protein",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="food_details",
            name="serving_size",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
