# Generated by Django 5.0.6 on 2024-06-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_food_details_calories_alter_food_details_carbs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
    ]
